### ISSUE TITLE
6x MaxCam/MaxCam.lua:145: attempt to index local 'panel' (a nil value)

### ISSUE THREAD

**Issue by Inniebins** [ketho-wow/MaxCam#2]
I am getting this error ingame:

6x MaxCam/MaxCam.lua:145: attempt to index local 'panel' (a nil value)
[string "@MaxCam/MaxCam.lua"]:145: in function <MaxCam/MaxCam.lua:143>
[string "=[C]"]: ?
[string "=[C]"]: in function `Show'
[string "@BagBrother/libs/Sushi-3.1-5/classes/groups/Options.lua"]:73: in function `Open'
[string "@Bagnon/src/optionsToggle.lua"]:29: in function <Bagnon/src/optionsToggle.lua:26>

**Comment by Ketho** [comment]
Oh this should have been fixed in the recent [v2.6.2](https://github.com/ketho-wow/MaxCam/releases/tag/v2.6.2) release
